version: "3"

services:
  oracle:
    image: roothunter/uniba/database-systems/oraclelinux
    build: .
    container_name: oraclelinux-container
    tty: true #Enables an interactive terminal session

    #volumes:
    #  - ./config/listener.ora:/opt/oracle/product/23c/dbhomeFree/network/admin/listener.ora

    ports:
      - 1512:1512 #Share the default Oracle Database port with host machine
    networks:
      - oraclelinux-network

networks:
  oraclelinux-network: